a = int(input("Ievadit skaitlis: " ))
b = int(input("Ievadit skaitlis: " ))
print(a ** b)
c = int(input("Ievadit skaitlis: " ))
print(a ** c)
d = int(input("Ievadit skaitlis: " ))
print(a ** d)
e = int(input("Ievadit skaitlis: " ))
print(a ** e)
f = int(input("Ievadit skaitlis: " ))
print(a ** f)
g = int(input("Ievadit skaitlis: " ))
print(a ** g)
h = int(input("Ievadit skaitlis: " ))
print(a ** h)
i = int(input("Ievadit skaitlis: " ))
print(a ** i)